name: Testing top-level contents write permissions with sigle job calling an action from github
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  action-from-github-without-job-level-permission:
    runs-on: ubuntu-latest
    name: Call github action with write permission inherited from top-level permissions

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
        with:
          persist-credentials: false