name: Testing job-level write permissions with a top-level read-all
on:
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  third-party-action-with-contents-write:
    runs-on: ubuntu-latest
    name: Call third party action with write permission
    permissions:
      contents: write

    steps:
      - name: "Checkout code"
        uses: not-really-safe-source/arguably-dangerous-action@master